name: Deploy to KillerKoda
 
on:
  push:
    branches:
      - main
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
 
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest
 
      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          # kubectl --kubeconfig=kubeconfig config use-context kubernetes-admin@kubernetes
          
      - name: Apply k8s manifests
        run: |
          kubectl --kubeconfig=kubeconfig apply -f k8s/deployment.yaml
        
 
      # - name: Deploy to Cluster
      #   run: |
      #     # kubectl --kubeconfig=kubeconfig apply -f k8s/deployment.yaml --validate=false
      #     kubectl --kubeconfig=kubeconfig apply -f k8s/deployment.yaml --validate=false --request-timeout=60s

      # - name: Deploy to Cluster
      #   run: |
      #     kubectl --kubeconfig=kubeconfig config get nodes  
